# Project information
site_name: OpenE8
site_description: 'Dokumentation zu OpenE8'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://openpotato.github.io/opene8/'

# Copyright
copyright: 
  '&copy; 2025 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/openpotato/opene8'

# Theming
theme:
  name: material
  language: de
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: 'red'
      accent: 'red'
      toggle:
        icon: material/brightness-7
        name: In den Dunkelmodus wechseln
    - scheme: slate
      primary: 'red'
      accent: 'red'
      toggle:
        icon: material/brightness-4
        name: In den Hellmodus wechseln
  font: false
  favicon: 'assets/logos/favicon.ico'
  logo: 'assets/logos/logo.svg'
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

# Social media & multi language
extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/openpotato.org
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@openpotato

# Customization
extra_css:
  - assets/css/custom.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Navigation
nav:
  - Einführung: index.md
  - Community: community.md
